kind: Deployment
apiVersion: apps/v1
metadata:
  name: oci-cloudag-api
  namespace: cloudag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oci-cloudag-api
  template:
    metadata:
      labels:
        app: oci-cloudag-api
    spec:
      containers:
      - name: oci-cloudag-api
        image: icn.ocir.io/cnjbjdrehgll/cloudag/oci-cloudag-api:0.1.0-211108
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: cloudagsecret
---
kind: Service
apiVersion: v1
metadata:
  name: oci-cloudag-api
  namespace: cloudag
  labels:
    app: oci-cloudag-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: oci-cloudag-api
  type: LoadBalancer
